Updated the tenant attribute to domain
test-kitchen/vmware-vra-gem pull request #102
Opened 2022-12-15 14:37 UTC by ashiqueps

Signed-off-by: Ashique P S <Ashique.saidalavi@progress.com>

# Description

vRA8 requires the domain attribute set when creating the VM, instead of the older tenant attribute. Today, the kitchen-vra gem passes the domain via the tenant attribute in the kitchen.yml file. This confuses users. This PR is to introduce a domain attribute (mark it required) and deprecate the existing tenant attribute.

The user needs to define the domain rather than the tenant in the kitchen.yml file when using the kitchen-vra plugin on the vRA8 setup.

## Issues Resolved

List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant

## Type of Change

Our release process assumes you are using [Conventional Commit messages](https://www.conventionalcommits.org/en/v1.0.0/).

The most important prefixes you should have in mind are:

- `_fix_`: which represents bug fixes, and correlates to a SemVer patch.
- `_feat_`: which represents a new feature, and correlates to a SemVer minor.
- `_feat!_`:, or `fix!:`, `refactor!:`, etc., which represent a breaking change (indicated by the !) and will result in a major version change.

If you have not included a conventional commit message this can be fixed on merge.

## Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [ ] Commit message includes a [Conventional Commit Message](https://www.conventionalcommits.org/en/v1.0.0)

2022-12-15 15:09 UTC, Xorima requested changes
Please ensure there is clear documentation for people upgrading as this will need to be a major version change due to the behaviour change.

2022-12-15 17:57 UTC, ashiqueps commented
Hi @Xorima 

I've updated the documentation of this gem in this PR itself. Also, the PR that adds `domain` and deprecates `tenant` in `kitchen-vra` repo is almost ready and will be raised once this one is merged and the version is released to Rubygems, which will have the version pinning as well. 

I've another PR also ready to update the `kitchen.ci` documentation as well.

2022-12-16 04:05 UTC, sanjain-progress approved these changes

2022-12-16 14:47 UTC, ashiqueps commented
@Xorima,

The major version bumps we have done in this gem are whenever we add support for the major vRA versions. The change we introduced in this PR is minor and is [backwards compatible](https://github.com/test-kitchen/vmware-vra-gem/pull/102/files#diff-69707c1864a81a24617b6452b8aa9aa3b14e3019a47199432359629d5691f6d7R249) as well. Should we go for a major release for this change?

cc: @tas50

2022-12-17 10:19 UTC, Xorima commented
Thanks @ashiqueps , I missed the bit in `    def fetch_domain(opts)` where we look and decide based on logic, sorry mate, happy for this to go ahead.

2022-12-17 10:19 UTC, Xorima approved these changes

2022-12-17 16:15 UTC, merged